### ISSUE TITLE
ナレーション: 自動読み上げか、私igrepが読むか

### ISSUE THREAD

**Issue by igrep** [igrep/intro-mdn-translation-ja#2]
読み上げにはigrepはそれなりに慣れているものの、メンテナンスしやすさを考えるとVOICEVOXなど無償で使える読み上げエンジンを使った方がいい？

**Comment by potappo** [comment]
igrep さんのナレーションでもかまわないですが、VOICEVOX などの読み上げエンジンも確かに便利そうと思います。

https://voicevox.hiroshiba.jp/

VOICEVOX だけでもけっこうたくさんキャラクターがいるので、どれにするかという別の悩みが発生しそうですね。説明ナレーションに合ったキャラクター、説明が聞きやすければ良いと思います。igrep さんのおすすめがあればそれでもかまいません。

良さそうな読み上げエンジンがあればそれを使ってみる、選定に時間かかるようなら、igrep さんが読むという方針で良いかと思います。

**Comment by igrep** [comment]
> 説明ナレーションに合ったキャラクター、説明が聞きやすければ良いと思います

確かに！結局それが一番大事な観点ですね！

**Comment by hmatrjp** [comment]
potappoさんの意見に同意した上で、私は、igrepさんの楽な方法を選ぶのがいいのかなと思っています。

MDNミートアップ（オンライン）の報告会で聞いている限り、igrepさんの声も聞こえやすいと思うので。

一点だけメモ：　VOICEVOXのトップページにあるサンプルを聞くと、私のヘッドセットではところどころ音割れします。
（調整できるエンコードパラメーターの問題？）

**Comment by igrep** [comment]
こちら、みなさんの後押しもあり、私の中で「機械音声をいろいろ調べるより自分で読む方がモチベーションが高いなぁ」という気持ちになってきたので自分で録ることにします（とりあえず動画を撮るところからやるので気が変わったらまた変えるかも知れませんが 😅 ）。ご意見ありがとうございました！
