### ISSUE TITLE
動画編集ソフト

### ISSUE THREAD

**Issue by igrep** [igrep/intro-mdn-translation-ja#3]
現状、無償で使えるのでDaVinci Resolveというのを使おうかと検討しています。
こちらも完成後に再編集するケースを考えると、編集データの形式に縛られてしまう恐れがあるので、どのアプリケーションを使うか話しあっておきたいです。

**Comment by hmatrjp** [comment]
いろいろなアプリ共通で使える動画形式で保存することを決めておけば大丈夫ではないでしょうか。
（コンテナ、ビデオ、音声それぞれについて）
私は [OpenShot Video Editor](https://www.openshot.org/ja/)  を使う都合で、編集時のコンテナにMKVを使うことが多いです。

**Comment by igrep** [comment]
OpenShot Video Editor 存じませんでした！一応他のアプリの事情も調査しますが、それでよさそうですね。

**Comment by igrep** [comment]
こちら、私の中であれこれ調べるやる気が失せてきたので、OpenShot Video Editorを使う方向で進めます。
ご意見ありがとうございました！
